services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    ports:
      - "${DOCKER_CLIENT_PORT}:${DOCKER_CLIENT_PORT}"
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - server
    volumes:
      - ./client:/app

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    ports:
      - "${DOCKER_SERVER_PORT}:${DOCKER_SERVER_PORT}"
    volumes:
      - "./server:/app"
